spring:
  datasource:
    url: jdbc:mysql://database-rds-5-7.csy6mndvaztr.ap-northeast-2.rds.amazonaws.com:3306/EUIHEE_PHOTO
    username: root
    password: alsltkfkd5
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    template-resolver-order: 0
